### ISSUE TITLE
Array element[0] returns no results with SEaMS + Compose.io Redis

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/seams#5]
Super weird, but if you go to my demo app using the optional Redis service at http://seams-broberg-1040.mybluemix.net/admin/search you'll see all the nice facets. Try searching for genre:'C' and it works beautifully. So do all the other elements except for genre:'A'

Pretty sure this is related to the Redis cache option, because this was working perfectly yesterday with the default IBM cache. Thanks.

Dataset at https://www.dropbox.com/s/4fp7v7ikndtbc1p/movieSEaMS_001.tsv?dl=0

**Comment by glynnbird** [comment]
It's not a cache thing. You can test this by accessing the Seams API directly and adding `cache=false` to the query to instruct seams to not use cache e.g.

    http://seams-broberg-1040.mybluemix.net/search?q=genre:C&cache=false

which works

    http://seams-broberg-1040.mybluemix.net/search?q=genre:A&cache=false

does not. If you send me your data I'll try and work out what's going on.

**Comment by mikebroberg** [comment]
Yep. I provided the data in my original issue above. Dataset at https://www.dropbox.com/s/4fp7v7ikndtbc1p/movieSEaMS_001.tsv?dl=0

You're right that it's not a cache thing. I properly deployed Redis this morning by changing the name to "Redis by Compose" and this issue still happens. This was working on Monday I swear.

**Comment by glynnbird** [comment]
It turns out that "a" is a stopword when using the default analyzer in Cloudant Search, so "a" wasn't indexed (but was considered a unique value for faceting).
